### PR TITLE
feat: uniform favicon and add Starlight Steps component

### LINKED ISSUE #27: feature request: icon size and lettering size on Taiko docs tab
Icons and lettering are a different size on page tab when compared to other page tabs https://docs.taiko.xyz/start-here/getting-started

image

### PR DESCRIPTION
**Pull request by brachsterX**
Resolves #27 and #110

### CODE REVIEW

**Comment by RogerLamTd** [comment]
@brachsterX Not sure the package-lock should be included, otherwise lgtm

**Review by RogerLamTd — APPROVED** [review]

**Comment by brachsterX** [comment]
@RogerLamTd deleted! 😄

**Comment by RogerLamTd** [comment]
@brachsterX sorry, looks like some more conflicts :) hopefully this doesn't break everything again haha

**Comment by brachsterX** [comment]
I think I did it right this time @RogerLamTd 😄

**Comment by RogerLamTd** [comment]
@brachsterX It looks like vercel is having trouble deploying it so there must be some issue, also the favicon doesn't display for me; could you try pushing fixes? 
Screenshot 2024-05-06 at 11 53 11 AM

**Comment by RogerLamTd** [comment]
> > @brachsterX It looks like vercel is having trouble deploying it so there must be some issue, also the favicon doesn't display for me; could you try pushing fixes? Screenshot 2024-05-06 at 11 53 11 AM
> 
> Weird it did that. Pushed a fix to it.

@brachsterX Still issues, please do make changes and do `pnpm build` + `pnpm preview` locally to make sure it works
`07:45:20   ├─ /guides/run-a-taiko-node/index.html[AstroUserError] The <Steps> component expects its content to be a single ordered list but found multiple child elements `

**Review by RogerLamTd — APPROVED** [review]
LGTM

**Comment by d1onys1us** [comment]
@brachsterX, but this is too difficult to review. In the interest of time, I'll just submit a small stack of PRs which are easier to review.

This is how you could otherwise improve it. There are two ways you can submit a better PR for review:

1. Separate the PR into multiple logical commits. This means the commit history could look like:
- abcd: add new favicon
- efgh: migrates files from md to mdx
- klmn: wraps steps in a step component

This makes it so the reviewer can clearly verify each commit / change easily one by one. You would probably need to do an interactive rebase.

2. Separate the PR into [stacked PRs](https://benjamincongdon.me/blog/2022/07/17/In-Praise-of-Stacked-PRs/) (multiple small PRs for each feature). This would be like

main <- PR-1: add new favicon
PR-1 <- PR-2: migrates files from md to mdx
PR-2 <- PR-3: wraps steps in a step component.

Same thing here, the reviewer can easily see the changes. Right now the PR diff is too messy, so it's difficult to review.

We want to make sure that PRs are small, atomic, easy to review, and only affect a single set of features. Thanks for the contribution.

**Pull request closed without merging**
